### ISSUE TITLE
Credentials Client and Server are deleting TokenB

### ISSUE THREAD

**Issue by atschabu** [IZIVIA/ocpi-toolkit#15]
I've been evaluating this library and found an inconsistency with the credentials module. According to the documentation 

>  The Receiver stores CREDENTIALS_TOKEN_B and uses it for any requests to the Sender Platform, including the version information and details

yet it looks like this library is discarding CREDENTIALS_TOKEN_B together with TOKEN_A on successful registration, and is only using CREDENTIALS_TOKEN_C for receiving and sending requests:

https://github.com/IZIVIA/ocpi-toolkit/blob/493f34775934d53b8559cf18df7ff4a50aaf2542/ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/modules/credentials/services/CredentialsClientService.kt#L108

Shouldn't the B token be kept, and the credentials include some kind of hint if the platform is either the receiver or sender?

**Comment by lilgallon** [comment]
Thanks for your feedback, you are absolutely right. The receiver has to use Token B to communicate with the sender. There was also a discussion about that here: https://github.com/ocpi/ocpi/issues/166

So, the token B **has to be kept**, and the **token C** should not. Then, to know which token to use, there are two cases:
- The platform only has either token B or token C. In that case, use the one that exists
- The platform has both of them. Because at some point both systems registered with the other. I am not sure about the solution yet. In that case, the caller knows if the call is made as a CPO or as an eMSP. So I guess that the lib should offer the possibility to choose the token to use for the call.

**Comment by atschabu** [comment]
you always need to keep B and C .. because you need one to verify the incoming requests, and the other to send requests.

I think it might be easier to use something along the lines of 'our token' and 'their token' instead of B / C, as B and C is relative to whether you were the receiver or sender, while Ours and Theirs would be absolute from server / client perspective

This way a server will always compare authorization header against "their token" and a clients will emit "our token"

**Comment by lilgallon** [comment]
Yes you are right I forgot that part. I really like this approach of storing two tokens, one being ours, and the other one being theirs. It removes the hassle of picking the right token at the right time.

It will be fixed this in the next version. Thanks again for your feedback

**Comment by lilgallon** [comment]
It's fixed in https://github.com/IZIVIA/ocpi-toolkit/releases/tag/R-0.0.14 for ocpi 2.2.1. This version is the priority right now, but the changes will be made on 2.1.1 & 2.1.1-gireve later on
