### ISSUE TITLE
last_updated must be updated in EVSE and Location objects

### ISSUE THREAD

**Issue by andacata** [IZIVIA/ocpi-toolkit#67]
The documentation states that (8.2.2.2. PUT Method):

> When the PUT only contains a Connector Object, the Receiver SHALL also set the new last_updated value on the parent EVSE and Location Objects.
>
> When the PUT only contains a EVSE Object, the Receiver SHALL also set the new last_updated value on the parent Location Object.

But the toolkit is not doing that. This can be done in the repository implementation, letting the users of the library to implement it, but I think it's not the best approach.

What do you think?

**Comment by lilgallon** [comment]
To be clear, you are speaking about the `LocationsEmspRepository`. Currently each one of the methods match a specific Http endpoint.

Your idea is to have something like:

```kotlin
req.httpResponse {
    service
        .patchEvse(
            countryCode = req.pathParams["countryCode"]!!,
            partyId = req.pathParams["partyId"]!!,
            locationId = req.pathParams["locationId"]!!,
            evseUid = req.pathParams["evseUid"]!!,
            evse = mapper.readValue(req.body!!, EvsePartial::class.java)
        )
        .also {
            service.updateLocationLastUpdated(
                countryCode = xxx,
                partyId = yyy,
                locationId = zzz,
                lastUpdated = it.data.lastUpdated
            )
        }
}
```

And the same thing for `patchConnector` (but that also updates evse last_updated.

----

I see several issues to this approach:
- Each patch now requires two calls, (two potential database operations) instead of one
- It is harder to handle what is happening during a patch because the response can be an error even though the patch worked properly (`patchEvse` success, `updateLocationLastUpdated` throws an error). In that case, we may not want to perform `patchEvse` -> we do not have the control on it

The initial approach was to give full responsability to the person that implement the lib. The lib offers an abstraction over HTTP calls, and the person just has to implement what is supposed to be done on each HTTP call without any more abstraction layer.

We added abstraction on complex tasks (for instance in credentials module), but for the rest, as of now, we do not think it is required, and it may be better to give some freedom to the person that implement the endpoints

**Comment by atschabu** [comment]
I concur with @lilgallon that this is a problem to be solved by implementor, as you can not infer the data structure and read/write paths used.

For example you could solve the last_updated as part of the read path, by checking all children, and setting the parents last_updated to max value. You might also have an implementation where you keep all the rapidly changing fields (status, last_updated) in a different store, and automatically update the parent as part of updating the children.

It is better to let implementor choose a solution, and handle a single call, instead of artificially creating more calls that might reduce efficiency of the system, just in case someone didn't read the manual.

Furthermore your suggestion would only solve the issue on the Receiver side, as on the Sender side, where you are consuming updates from an internal system you'd still need to handle the problem of updating parents last_updated. Which is also the more problematic side, as for the most part, it doesn't matter to much if the emsp updates their last_updated of a parent properly, as they don't have a search endpoint requiring that field to work correctly.

**Comment by andacata** [comment]
I think that it's a functional requirement of the protocol, so it's the library's `xxxxService` responsibility, but I see your point (both).

I'm closing the issue.
